type CGMaya_config.py >> total.txt
type CGMaya_main.py >> total.txt
type CGMaya_dialog.py >> total.txt
type CGMaya_function.py >> total.txt
type CGMaya_export.py  >> total.txt
type CGMaya_login.py  >> total.txt
type CGMaya_open.py   >> total.txt
type CGMaya_common.py >> total.txt
type CGMaya_save.py  >> total.txt
type CGMaya_reference.py >> total.txt
type CGMaya_setup.py  >> total.txt
type CGMaya_parser.py >> total.txt
type CGMaya_submit.py >> total.txt
type CGMaya_service.py >> total.txt
type CGMaya_logger.py >> total.txt
type CGMaya_aniCapture.py >> total.txt
type CGMaya_assetCapture.py >> total.txt
type CGMaya_checkin.py  >> total.txt
type RWingForMaya.py >> total.txt
